spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:jornada_milhas}'
    username: ${DATABASE_USER:itslucassantos}
    password: ${DATABASE_PASSWORD:7149}
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: Always