server:
  port: 8081

openai:
  api_key: ${OPENAI_API_KEY}

spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:jornada_milhas}'
    username: ${DATABASE_USER:${DB_USER}}
    password: ${DATABASE_PASSWORD:${DB_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: Always

  jpa:
    show-sql: true
    format-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB